# Comments marked with *TODO* are the customization points where you should adjust the text of this workflow template to the
# needs of your your repo.
name: "CI: Build, Test, Benchmark"

on:
  push:
    branches:
      - "**" # trigger on push for all branches or...

  pull_request:
    branches:
      - "**" # ...on PR for all branches.

  workflow_dispatch:
    inputs:
      runners-os:
        description: Comma-separated runners OS-es
        type: string
        default: ubuntu-latest # *TODO* Adjust the default runner OS or OS-es as needed.
        # Note: there is a known GitHub actions issue: the workflow dispatch UI doesn't properly handle JSON strings with quotes -
        # it removes the quotes. E.g. entering '["ubuntu-latest"]' in the UI prompt removes the inner quotes and it becomes the
        # invalid JSON: '[ubuntu-latest]'.

      preprocessor-symbols:
        description: Comma-separated preprocessor symbols
        type: string
        default: "SHORT_RUN" # *TODO* Adjust the default preprocessor symbols as needed.

env:
  # The value of all *_PROJECTS variables must be specified as a string containing a JSON array of strings - path(s) to
  # the project(s).
  # Note the yaml folding indicator `>-`. It allows to enter single line, scalar, string values on multiple lines, which might
  # be more readable, and writable (no escaping etc.).

  # If not specified, the default is the root solution or the project in src/.
  # *TODO* The source code project(s) to build. JSON array of path(s) to the project(s).
  BUILD_PROJECTS: >
    [
    "src/Project/Project.slnx"
    ]

  # If not specified, no tests will be built or run. Not having tests is not typical and not desirable, but on rare occasions - possible.
  TEST_PROJECTS: "" # *TODO* The test project(s) to build and run. JSON array of path(s) to the test project(s).

  BENCHMARK_PROJECTS: "" # *TODO* The benchmark project(s) to build and run. JSON array of path(s) to the benchmark project(s).
  # If not specified, the default is ["ubuntu-latest"].
  # *TODO* The OS-es of the runner(s) to use for building and testing. JSON array of OS-es.

  RUNNERS_OS: >
    [
    "ubuntu-latest"
    ]

  PREPROCESSOR_SYMBOLS: "" # *TODO* Space or comma or semicolon-separated preprocessor symbols to pass to the compiler.

  DOTNET_VERSION: ${{ vars.DOTNET_VERSION || '10.0.x' }} # The .NET SDK version to use.
  CONFIGURATION: ${{ vars.CONFIGURATION || 'Release' }} # The build configuration: Debug, Release, etc.
  MIN_COVERAGE_PCT: ${{ vars.MIN_COVERAGE_PCT || 80 }} # The minimum code coverage percentage required to pass the tests.
  MAX_REGRESSION_PCT: ${{ vars.MAX_REGRESSION_PCT || 20 }} # The maximum allowed performance regression percentage for benchmarks to pass.
  MINVERTAGPREFIX: ${{ vars.MINVERTAGPREFIX || 'v' }} # The MinVer tag prefix.
  MINVERDEFAULTPRERELEASEIDENTIFIERS: ${{ vars.MINVERDEFAULTPRERELEASEIDENTIFIERS || 'preview.0' }} # The MinVer default pre-release identifiers.
  VERBOSE: ${{ vars.VERBOSE || 'false' }} # Set to "true" to enable verbose logging in scripts.

jobs:
  get-params:
    name: Finalize parameters from variables, inputs, secrets and defaults
    runs-on: ubuntu-latest # in this workflow the runner doesn't matter - we're just preparing the inputs for the next workload(s).
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]') }}
    outputs:
      build-projects: ${{ steps.init-params.outputs.build-projects }}
      test-projects: ${{ steps.init-params.outputs.test-projects }}
      benchmark-projects: ${{ steps.init-params.outputs.benchmark-projects }}
      runners-os: ${{ steps.init-params.outputs.runners-os }}
      dotnet-version: ${{ steps.init-params.outputs.dotnet-version }}
      configuration: ${{ steps.init-params.outputs.configuration }}
      preprocessor-symbols: ${{ steps.init-params.outputs.preprocessor-symbols }}
      min-coverage-pct: ${{ steps.init-params.outputs.min-coverage-pct }}
      max-regression-pct: ${{ steps.init-params.outputs.max-regression-pct }}
      minver-tag-prefix: ${{ steps.init-params.outputs.minver-tag-prefix }}
      minver-prerelease-id: ${{ steps.init-params.outputs.minver-prerelease-id }}
    steps:
      - name: Gather parameters
        id: init-params
        shell: bash
        run: |
          build_projects='${{ env.BUILD_PROJECTS }}'
          test_projects='${{ env.TEST_PROJECTS }}'
          benchmark_projects='${{ env.BENCHMARK_PROJECTS }}'
          runners_os='${{ env.RUNNERS_OS }}'
          dotnet_version='${{ env.DOTNET_VERSION }}'
          configuration='${{ env.CONFIGURATION }}'
          preprocessor_symbols='${{ env.PREPROCESSOR_SYMBOLS }}'
          min_coverage_pct='${{ env.MIN_COVERAGE_PCT }}'
          max_regression_pct='${{ env.MAX_REGRESSION_PCT }}'
          minver_tag_prefix='${{ env.MINVERTAGPREFIX }}'
          minver_prerelease_id='${{ env.MINVERDEFAULTPRERELEASEIDENTIFIERS }}'

          if [ '${{ github.event_name }}' == "push" ]; then
              # Set the values for push events, and add SHORT_RUN to preprocessor_symbols for faster benchmark tests (less precise, yet acceptable for CI runs).
              preprocessor_symbols="${preprocessor_symbols};SHORT_RUN"
          elif [ '${{ github.event_name }}' == "workflow_dispatch" ]; then
              # Get the values from the UI inputs of workflow_dispatch event. Convert comma-separated runners' OS values to JSON array
              # There is a known GitHub actions issue: the workflow dispatch UI doesn't properly handle JSON strings with quotes.
              # E.g. for the input '["ubuntu-latest"]', the UI removes the inner quotes and it becomes the invalid JSON: '[ubuntu-latest]'.
              runners_os=$(echo "${{ inputs.runners-os }}" | jq -Rc 'split(",") | map(select(length > 0) | gsub("^\\s+|\\s+$";""))')
              preprocessor_symbols="${preprocessor_symbols};${{ inputs.preprocessor-symbols }}"
          else
              echo "Unsupported event: ${{ github.event_name }}"
              exit 5
          fi

          # Set the outputs:
          {
              echo "build-projects=${build_projects}"
              echo "test-projects=${test_projects}"
              echo "benchmark-projects=${benchmark_projects}"
              echo "runners-os=${runners_os}"
              echo "dotnet-version=${dotnet_version}"
              echo "configuration=${configuration}"
              echo "preprocessor-symbols=${preprocessor_symbols}"
              echo "min-coverage-pct=${min_coverage_pct}"
              echo "max-regression-pct=${max_regression_pct}"
              echo "minver-tag-prefix=${minver_tag_prefix}"
              echo "minver-prerelease-id=${minver_prerelease_id}"
          }  >> $GITHUB_OUTPUT

  call-ci:
    name: Build, Test, Benchmarks
    needs:
      - get-params
    uses: vmelamed/vm2.DevOps/.github/workflows/_ci.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    permissions:
      contents: read # Required to checkout the code
      packages: read # Required to restore GitHub Packages NuGet packages
      pull-requests: write # Required to comment on PRs
      checks: write # Required to create GitHub Checks
    with:
      build-projects: ${{ needs.get-params.outputs.build-projects }}
      test-projects: ${{ needs.get-params.outputs.test-projects }}
      benchmark-projects: ${{ needs.get-params.outputs.benchmark-projects }}
      runners-os: ${{ needs.get-params.outputs.runners-os }}
      dotnet-version: ${{ needs.get-params.outputs.dotnet-version }}
      configuration: ${{ needs.get-params.outputs.configuration }}
      preprocessor-symbols: ${{ needs.get-params.outputs.preprocessor-symbols }}
      min-coverage-pct: ${{ fromJSON(needs.get-params.outputs.min-coverage-pct) }}
      max-regression-pct: ${{ fromJSON(needs.get-params.outputs.max-regression-pct) }}
      minver-tag-prefix: ${{ needs.get-params.outputs.minver-tag-prefix }}
      minver-prerelease-id: ${{ needs.get-params.outputs.minver-prerelease-id }}
