# Comments marked with *TODO* are the customization points where you should adjust the text of this workflow template to the
# needs of your your repo.
name: "CI: Build, Test, Benchmark, Pack"

on:
  push:
    branches:
      - "**" # trigger on push for all branches

  pull_request:
    branches:
      - "**" # trigger on PR for all branches.

  workflow_dispatch:
    inputs:
      runners-os:
        description: Comma-separated runners OS-es
        type: string
        default: ubuntu-latest # *TODO* Adjust the default runner OS or OS-es as needed.
        # Note: there is a known GitHub actions issue: the workflow dispatch UI doesn't properly handle JSON strings with quotes -
        # it removes the quotes. E.g. entering '["ubuntu-latest"]' in the UI prompt removes the inner quotes and it becomes the
        # invalid JSON: '[ubuntu-latest]'.

      preprocessor-symbols:
        description: Comma-separated preprocessor symbols
        type: string
        default: "SHORT_RUN" # *TODO* Adjust the default preprocessor symbols as needed.

# Concurrency: cancel in-progress runs for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  # The value of all *_PROJECTS variables must be specified as a string containing a JSON array of strings - path(s) to
  # the project(s).
  # Note the yaml folding indicator `>-`. It allows to enter single value (scalar, array, object, long string) values on
  # multiple text lines with no need for escaping, which might be more readable, and writable.

  # If not specified or empty, no actual building will be run (e.g. template projects).
  # *TODO* The source code project(s) or solution(s) to build. Must be a JSON array of strings containing path(s) to the buildable project(s) or solution(s).
  BUILD_PROJECTS: >
    [
    "src/Project/Project.slnx"
    ]

  # If not specified or empty, no tests will be built or run. Not having tests is not typical and not desirable, but possible.
  # For example projects that contain only the code of the deliverables, e.g. projects in early stages of development, or DevOps
  # projects containing scripts and/or markup and/or metadata, template projects, prototype projects, experimentation, etc.
  # *TODO* The test project(s) to build and run. Must be a JSON array of strings containing path(s) to the buildable and runnable test project(s).
  TEST_PROJECTS: "[]"

  # If not specified or empty, no benchmarks will be built or run.
  # *TODO* The benchmark project(s) to build and run. Must be a JSON array of strings containing path(s) to the buildable and runnable benchmark project(s).
  BENCHMARK_PROJECTS: "[]"

  # If not specified or empty, no projects will be packed for NuGet validation during CI.
  # *TODO* The project(s) to pack for NuGet validation during CI. Must be a JSON array of strings containing path(s) to the packable project(s).
  PACKAGE_PROJECTS: "[]"

  # If not specified, the default is ["ubuntu-latest"].
  # *TODO* The OS-es of the runner(s) to use for building and testing. Must be a JSON array of strings containing OS-es.
  RUNNERS_OS: >
    [
    "ubuntu-latest"
    ]

  PREPROCESSOR_SYMBOLS: "" # *TODO* Space or comma or semicolon-separated preprocessor symbols to pass to the compiler.

  DOTNET_VERSION: ${{ vars.DOTNET_VERSION || '10.0.x' }} # The .NET SDK version to use.
  CONFIGURATION: ${{ vars.CONFIGURATION || 'Release' }} # The build configuration: Debug, Release, etc.
  MIN_COVERAGE_PCT: ${{ vars.MIN_COVERAGE_PCT || 80 }} # The minimum code coverage percentage required to pass the tests.
  MAX_REGRESSION_PCT: ${{ vars.MAX_REGRESSION_PCT || 20 }} # The maximum allowed performance regression percentage for benchmarks to pass.
  MINVERTAGPREFIX: ${{ vars.MINVERTAGPREFIX || 'v' }} # The MinVer tag prefix.
  MINVERDEFAULTPRERELEASEIDENTIFIERS: ${{ vars.MINVERDEFAULTPRERELEASEIDENTIFIERS || 'preview.0' }} # The MinVer default pre-release identifiers.
  VERBOSE: ${{ vars.VERBOSE || 'false' }} # Set to "true" to enable verbose logging in scripts.

jobs:
  get-params:
    name: Prepare input from env, vars, secrets, inputs, and defaults
    runs-on: ubuntu-latest # in this workflow the runner doesn't matter - we're just preparing the inputs for the next workload(s).
    permissions:
      pull-requests: read
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    outputs:
      build-projects: ${{ steps.init-params.outputs.build-projects }}
      test-projects: ${{ steps.init-params.outputs.test-projects }}
      benchmark-projects: ${{ steps.init-params.outputs.benchmark-projects }}
      package-projects: ${{ steps.init-params.outputs.package-projects }}
      runners-os: ${{ steps.init-params.outputs.runners-os }}
      dotnet-version: ${{ steps.init-params.outputs.dotnet-version }}
      configuration: ${{ steps.init-params.outputs.configuration }}
      preprocessor-symbols: ${{ steps.init-params.outputs.preprocessor-symbols }}
      min-coverage-pct: ${{ steps.init-params.outputs.min-coverage-pct }}
      max-regression-pct: ${{ steps.init-params.outputs.max-regression-pct }}
      minver-tag-prefix: ${{ steps.init-params.outputs.minver-tag-prefix }}
      minver-prerelease-id: ${{ steps.init-params.outputs.minver-prerelease-id }}
      skip-push: ${{ steps.init-params.outputs.skip-push }}
    steps:
      - name: Prepare argument values
        id: init-params
        shell: bash
        run: |
          build_projects='${{ env.BUILD_PROJECTS || "[]" }}'
          test_projects='${{ env.TEST_PROJECTS || "[]" }}'
          benchmark_projects='${{ env.BENCHMARK_PROJECTS || "[]" }}'
          package_projects='${{ env.PACKAGE_PROJECTS || "[]" }}'
          runners_os='${{ env.RUNNERS_OS || "[\"ubuntu-latest\"]" }}'
          dotnet_version='${{ env.DOTNET_VERSION || "10.0.x" }}'
          configuration='${{ env.CONFIGURATION || "Release" }}'
          preprocessor_symbols='${{ env.PREPROCESSOR_SYMBOLS || "" }}'
          min_coverage_pct='${{ env.MIN_COVERAGE_PCT || 80 }}'
          max_regression_pct='${{ env.MAX_REGRESSION_PCT || 20 }}'
          minver_tag_prefix='${{ env.MINVERTAGPREFIX || "v" }}'
          minver_prerelease_id='${{ env.MINVERDEFAULTPRERELEASEIDENTIFIERS || "preview.0" }}'
          skip_push='false'

          if [ '${{ github.event_name }}' == "pull_request" ] || \
             ([ '${{ github.event_name }}' == "push" ] && [ '${{ github.ref_name }}' == "main" ]); then

              # For pull requests, reviews, and pushes to the main branch, use default values from env (no modifications needed)
              echo "ℹ️  INFO: Event: ${{ github.event_name }}. Using default parameters from env." >> $GITHUB_STEP_SUMMARY

          elif [ '${{ github.event_name }}' == "push" ] && [ '${{ github.ref_name }}' != "main" ]; then

              # Skip push-triggered CI when an open PR exists for this branch.

              export GH_TOKEN='${{ github.token }}'

              if ! open_pr_count=$(gh pr list \
                --repo "${{ github.repository }}" \
                --state open \
                --json headRefName \
                --jq 'map(select(.headRefName == "${{ github.ref_name }}")) | length'); then
                open_pr_count=0
                echo "⚠️  WARNING: Failed to query PRs via gh. Running push-triggered CI with SHORT_RUN." >> $GITHUB_STEP_SUMMARY
              fi

              echo "ℹ️  INFO: Open PR count for '${{ github.ref_name }}': ${open_pr_count}" >> $GITHUB_STEP_SUMMARY

              if [ "${open_pr_count}" -gt 0 ]; then
                  echo "ℹ️  INFO: There are open PRs for this branch. Skipping push-triggered CI." >> $GITHUB_STEP_SUMMARY
                  skip_push='true'
              else
                  preprocessor_symbols="${preprocessor_symbols};SHORT_RUN"
                  echo "ℹ️  INFO: No open PRs for this branch. Running push-triggered CI with SHORT_RUN preprocessor symbol." >> $GITHUB_STEP_SUMMARY
              fi

          elif [ '${{ github.event_name }}' == "workflow_dispatch" ]; then

              # Get the values from the UI inputs of workflow_dispatch event. Convert comma-separated runners' OS values to JSON array
              # There is a known GitHub actions issue: the workflow dispatch UI doesn't properly handle JSON strings with quotes.
              # E.g. for the input '["ubuntu-latest"]', the UI removes the inner quotes and it becomes the invalid JSON: '[ubuntu-latest]'.

              runners_os=$(echo "${{ inputs.runners-os }}" | jq -Rc 'split(",") | map(select(length > 0) | gsub("^\\s+|\\s+$";""))')
              preprocessor_symbols="${preprocessor_symbols};${{ inputs.preprocessor-symbols }}"

          else

              echo "❌  ERROR: Unsupported event: ${{ github.event_name }}"
              exit 5

          fi

          # Set the outputs:
          {
              echo "build-projects=${build_projects}"
              echo "test-projects=${test_projects}"
              echo "benchmark-projects=${benchmark_projects}"
              echo "package-projects=${package_projects}"
              echo "runners-os=${runners_os}"
              echo "dotnet-version=${dotnet_version}"
              echo "configuration=${configuration}"
              echo "preprocessor-symbols=${preprocessor_symbols}"
              echo "min-coverage-pct=${min_coverage_pct}"
              echo "max-regression-pct=${max_regression_pct}"
              echo "minver-tag-prefix=${minver_tag_prefix}"
              echo "minver-prerelease-id=${minver_prerelease_id}"
              echo "skip-push=${skip_push}"
          }  >> $GITHUB_OUTPUT

  call-ci:
    name: "Run CI: Build, Test, Benchmark, Pack"
    needs:
      - get-params
    if: ${{ needs.get-params.outputs.skip-push != 'true' }}
    uses: vmelamed/vm2.DevOps/.github/workflows/_ci.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
      REPORTGENERATOR_LICENSE: ${{ secrets.REPORTGENERATOR_LICENSE }}
    permissions:
      contents: read # Required to checkout the code
      packages: read # Required to restore GitHub Packages NuGet packages
      pull-requests: write # Required to comment on PRs
      checks: write # Required to create GitHub Checks
    with:
      build-projects: ${{ needs.get-params.outputs.build-projects }}
      test-projects: ${{ needs.get-params.outputs.test-projects }}
      benchmark-projects: ${{ needs.get-params.outputs.benchmark-projects }}
      package-projects: ${{ needs.get-params.outputs.package-projects }}
      runners-os: ${{ needs.get-params.outputs.runners-os }}
      dotnet-version: ${{ needs.get-params.outputs.dotnet-version }}
      configuration: ${{ needs.get-params.outputs.configuration }}
      preprocessor-symbols: ${{ needs.get-params.outputs.preprocessor-symbols }}
      min-coverage-pct: ${{ fromJSON(needs.get-params.outputs.min-coverage-pct) }}
      max-regression-pct: ${{ fromJSON(needs.get-params.outputs.max-regression-pct) }}
      minver-tag-prefix: ${{ needs.get-params.outputs.minver-tag-prefix }}
      minver-prerelease-id: ${{ needs.get-params.outputs.minver-prerelease-id }}
