# Comments marked with *TODO* are the customization points where you should adjust the text of this workflow template to the
# needs of your your repo.
name: Publish NuGet Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*" # trigger on version tags like v1.2.3

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual release"
        required: true
        type: string

env:
  # The value of all *_PROJECTS variables must be specified as a string containing a JSON array of strings - path(s) to the
  # project(s).
  # Note the yaml folding indicator `>-`. It allows to enter single line, scalar, string values on multiple lines, which might
  # be more readable, and writable (no escaping etc.).

  # If not specified, the default is the root solution or the project in src/.
  # *TODO* The source code project(s) to build, package, and release as a stable release. JSON array of path(s) to the project(s).
  PACKAGE_PROJECTS: >-
    ["src/Project/Project.slnx"]

  # Ensure the NUGET_API_*KEY secret below corresponds to the server selected here.
  NUGET_SERVER: ${{ vars.NUGET_SERVER || 'github' }} # *TODO* 'github' - GitHub Packages; 'nuget' - NuGet.org; URI - others.

jobs:
  get-params:
    name: Prepare the parameters
    runs-on: ubuntu-latest
    if: >+
      ${{
      github.event_name == 'workflow_dispatch' ||
      !contains(github.ref_name,'-') &&
      startsWith(github.ref, format('refs/tags/%s', vars.MINVERTAGPREFIX || 'v'))
      }}
    outputs:
      dotnet-version: ${{ steps.init-params.outputs.dotnet-version }}
      package-projects: ${{ steps.init-params.outputs.package-projects }}
      nuget-server: ${{ steps.init-params.outputs.nuget-server }}
      minver-tag-prefix: ${{ steps.init-params.outputs.minver-tag-prefix }}
      reason: ${{ steps.init-params.outputs.reason }}
      save-package-artifacts: ${{ steps.init-params.outputs.save-package-artifacts }}
    steps:
      - name: Gather parameters
        id: init-params
        shell: bash
        run: |
          package_projects='${{ env.PACKAGE_PROJECTS }}'
          nuget_server='${{ env.NUGET_SERVER }}'
          dotnet_version='${{ vars.DOTNET_VERSION }}'
          minver_tag_prefix='${{ vars.MINVERTAGPREFIX || 'v' }}'
          reason="Stable Release (main was manually tagged with a release tag)"
          save_package_artifacts='${{ vars.SAVE_PACKAGE_ARTIFACTS || 'false' }}'

          if [ '${{ github.event_name }}' == "workflow_dispatch" ]; then
              reason='${{ inputs.reason }}'
          fi

          # Set the outputs:
          {
              echo "package-projects=${package_projects}"
              echo "nuget-server=${nuget_server}"
              echo "dotnet-version=${dotnet_version}"
              echo "minver-tag-prefix=${minver_tag_prefix}"
              echo "reason=${reason}"
              echo "save-package-artifacts=${save_package_artifacts}"
          }  >> $GITHUB_OUTPUT

  log-trigger:
    name: Log manual trigger reason
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Log manual trigger reason
        run: |
          echo "::notice::Manual release triggered by ${{ github.actor }}"
          echo "::notice::Reason: ${{ inputs.reason }}"

  release:
    name: Release - package and publish NuGet stable release
    needs:
      - get-params
    uses: vmelamed/vm2.DevOps/.github/workflows/_release.yaml@main
    secrets:
      # *TODO* The API key(s) for the NuGet server(s).
      # You don't need all three secrets, only the one corresponding to the chosen NuGet server above or the default 'github'
      NUGET_API_GITHUB_KEY: ${{ secrets.NUGET_API_GITHUB_KEY }}
      NUGET_API_NUGET_KEY: ${{ secrets.NUGET_API_NUGET_KEY }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    permissions:
      contents: write # Required to checkout the code and create releases
      packages: write # Required to publish GitHub Packages NuGet packages
      pull-requests: write # Required to comment on PRs
      checks: write # Required to create GitHub Checks
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      package-projects: ${{ needs.get-params.outputs.package-projects }}
      nuget-server: ${{ needs.get-params.outputs.nuget-server }}
      reason: ${{ needs.get-params.outputs.reason }}
      save-package-artifacts: ${{ fromJson(needs.get-params.outputs.save-package-artifacts) }}
      minver-tag-prefix: ${{ needs.get-params.outputs.minver-tag-prefix }}
