name: Publish NuGet Release
# After creating pay attention to the comments starting with CP - these are "Customize Points" to adjust the workflow to your repo needs.

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*" # trigger on version tags like v1.2.3

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual release"
        required: true
        type: string

env:
  # *TODO* The projects to build and package as a JSON array of strings - path(s) to the project(s).
  # An empty string means to build and package the root solution's projects or the root project, marked with <IsPackable>true</IsPackable>.
  # Hint: to set the value as a valid JSON list of strings, use YAML folded style (>-), and double quotes around the strings, e.g.:
  # BUILD_PROJECTS: >-
  #   ["src/Project1/Project1.csproj", "src/Project2/Project2.csproj"]
  PACKAGE_PROJECTS: >-
    ["src/Project/Project.sln"]
  # *TODO* 'github' - GitHub Packages; 'nuget' - NuGet.org. Make sure the NUGET_API_KEY secret corresponds to the server selected here.
  NUGET_SERVER: ${{ vars.NUGET_SERVER || 'github' }}

jobs:
  get-params:
    name: Prepare the parameters
    runs-on: ubuntu-latest
    if: >+
      ${{
      github.event_name == 'workflow_dispatch' ||
      !contains(github.ref_name,'-') &&
      startsWith(github.ref, format('refs/tags/%s', vars.MinVerTagPrefix || 'v'))
      }}
    outputs:
      package-projects: ${{ steps.init-params.outputs.package-projects }}
      nuget-server: ${{ steps.init-params.outputs.nuget-server }}
    steps:
      - name: Gather parameters
        id: init-params
        shell: bash
        run: |
          package_projects='${{ env.PACKAGE_PROJECTS }}'
          nuget_server='${{ env.NUGET_SERVER }}'

          # Set the outputs:
          {
              echo "package-projects=${package_projects}"
              echo "nuget-server=${nuget_server}"
          }  >> $GITHUB_OUTPUT

  log-trigger:
    name: Log manual trigger reason
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Log manual trigger reason
        run: |
          echo "::notice::Manual release triggered by ${{ github.actor }}"
          echo "::notice::Reason: ${{ inputs.reason }}"

  release:
    name: Release - package and publish NuGet stable release
    needs:
      - get-params
    uses: vmelamed/vm2.DevOps/.github/workflows/_release.yaml@main
    secrets:
      NUGET_API_GITHUB_KEY: ${{ secrets.NUGET_API_GITHUB_KEY }}
      NUGET_API_NUGET_KEY: ${{ secrets.NUGET_API_NUGET_KEY }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    permissions:
      contents: write # Required to checkout the code and create releases
      packages: write # Required to publish GitHub Packages NuGet packages
      pull-requests: write # Required to comment on PRs
      checks: write # Required to create GitHub Checks
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      package-projects: ${{ needs.get-params.outputs.package-projects }}
      nuget-server: ${{ needs.get-params.outputs.nuget-server }}
      reason: ${{ inputs.reason || '' }}
      save-package-artifacts: false
